//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace madurativas.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudio
    {
        public System.DateTime fechaestudio { get; set; }
        public string digitado { get; set; }
        public bool activo { get; set; }
        public decimal pacienteid { get; set; }
        public long estudioId { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual eval_riesgos eval_riesgos { get; set; }
        public virtual mchat mchat { get; set; }
    }
}
