//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace madurativas.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class mchat
    {
        public long estudio_id { get; set; }
        public Nullable<bool> quest_1 { get; set; }
        public Nullable<bool> quest_2 { get; set; }
        public Nullable<bool> quest_3 { get; set; }
        public Nullable<bool> quest_4 { get; set; }
        public Nullable<bool> quest_5 { get; set; }
        public Nullable<bool> quest_6 { get; set; }
        public Nullable<bool> quest_7 { get; set; }
        public Nullable<bool> quest_8 { get; set; }
        public Nullable<bool> quest_9 { get; set; }
        public Nullable<bool> quest_10 { get; set; }
        public Nullable<bool> quest_11 { get; set; }
        public Nullable<bool> quest_12 { get; set; }
        public Nullable<bool> quest_13 { get; set; }
        public Nullable<bool> quest_14 { get; set; }
        public Nullable<bool> quest_15 { get; set; }
        public Nullable<bool> quest_16 { get; set; }
        public Nullable<bool> quest_17 { get; set; }
        public Nullable<bool> quest_18 { get; set; }
        public Nullable<bool> quest_19 { get; set; }
        public Nullable<bool> quest_20 { get; set; }
        public bool completado { get; set; }
    
        public virtual estudio estudio { get; set; }
        public virtual mchat_monitor_quest_1 mchat_monitor_quest_1 { get; set; }
        public virtual mchat_monitor_quest_10 mchat_monitor_quest_10 { get; set; }
        public virtual mchat_monitor_quest_11 mchat_monitor_quest_11 { get; set; }
        public virtual mchat_monitor_quest_12 mchat_monitor_quest_12 { get; set; }
        public virtual mchat_monitor_quest_13 mchat_monitor_quest_13 { get; set; }
        public virtual mchat_monitor_quest_14 mchat_monitor_quest_14 { get; set; }
        public virtual mchat_monitor_quest_15 mchat_monitor_quest_15 { get; set; }
        public virtual mchat_monitor_quest_16 mchat_monitor_quest_16 { get; set; }
        public virtual mchat_monitor_quest_17 mchat_monitor_quest_17 { get; set; }
        public virtual mchat_monitor_quest_18 mchat_monitor_quest_18 { get; set; }
        public virtual mchat_monitor_quest_19 mchat_monitor_quest_19 { get; set; }
        public virtual mchat_monitor_quest_20 mchat_monitor_quest_20 { get; set; }
        public virtual mchat_monitor_quest_6 mchat_monitor_quest_6 { get; set; }
        public virtual mchat_monitor_quest_7 mchat_monitor_quest_7 { get; set; }
        public virtual mchat_monitor_quest_8 mchat_monitor_quest_8 { get; set; }
        public virtual mchat_monitor_quest_9 mchat_monitor_quest_9 { get; set; }
        public virtual mchat_monitor_quest_3 mchat_monitor_quest_3 { get; set; }
        public virtual mchat_monitor_quest_5 mchat_monitor_quest_5 { get; set; }
        public virtual mchat_monitor_quest_2 mchat_monitor_quest_2 { get; set; }
        public virtual mchat_monitor_quest_4 mchat_monitor_quest_4 { get; set; }
    }
}
